-- Canonical foods. Rows are added by migrations only.
create table foods (
    id              uuid         primary key default gen_random_uuid(),
    slug            varchar(64)  not null,
    name_es         varchar(80)  not null,
    name_en         varchar(80)  not null,
    category        varchar(16)  not null,
    default_unit    varchar(16)  not null,
    default_storage varchar(16)  not null,
    constraint uq_foods_slug unique (slug)
);

insert into foods (slug, name_es, name_en, category, default_unit, default_storage) values
    ('tomato',          'Tomate',              'Tomato',            'VEGETABLES', 'UNIT',       'REFRIGERATOR'),
    ('onion',           'Cebolla',             'Onion',             'VEGETABLES', 'UNIT',       'PANTRY'),
    ('garlic',          'Ajo',                 'Garlic',            'VEGETABLES', 'UNIT',       'PANTRY'),
    ('potato',          'Patata',              'Potato',            'VEGETABLES', 'KILOGRAM',   'PANTRY'),
    ('carrot',          'Zanahoria',           'Carrot',            'VEGETABLES', 'UNIT',       'REFRIGERATOR'),
    ('lettuce',         'Lechuga',             'Lettuce',           'VEGETABLES', 'UNIT',       'REFRIGERATOR'),
    ('zucchini',        'Calabacín',           'Zucchini',          'VEGETABLES', 'UNIT',       'REFRIGERATOR'),
    ('eggplant',        'Berenjena',           'Eggplant',          'VEGETABLES', 'UNIT',       'REFRIGERATOR'),
    ('red-pepper',      'Pimiento rojo',       'Red pepper',        'VEGETABLES', 'UNIT',       'REFRIGERATOR'),
    ('green-pepper',    'Pimiento verde',      'Green pepper',      'VEGETABLES', 'UNIT',       'REFRIGERATOR'),
    ('cucumber',        'Pepino',              'Cucumber',          'VEGETABLES', 'UNIT',       'REFRIGERATOR'),
    ('broccoli',        'Brócoli',             'Broccoli',          'VEGETABLES', 'UNIT',       'REFRIGERATOR'),
    ('cauliflower',     'Coliflor',            'Cauliflower',       'VEGETABLES', 'UNIT',       'REFRIGERATOR'),
    ('spinach',         'Espinacas',           'Spinach',           'VEGETABLES', 'GRAM',       'REFRIGERATOR'),
    ('mushroom',        'Champiñones',         'Mushrooms',         'VEGETABLES', 'GRAM',       'REFRIGERATOR'),
    ('leek',            'Puerro',              'Leek',              'VEGETABLES', 'UNIT',       'REFRIGERATOR'),
    ('pumpkin',         'Calabaza',            'Pumpkin',           'VEGETABLES', 'GRAM',       'PANTRY'),
    ('green-beans',     'Judías verdes',       'Green beans',       'VEGETABLES', 'GRAM',       'REFRIGERATOR'),
    ('apple',           'Manzana',             'Apple',             'FRUITS',     'UNIT',       'REFRIGERATOR'),
    ('banana',          'Plátano',             'Banana',            'FRUITS',     'UNIT',       'PANTRY'),
    ('orange',          'Naranja',             'Orange',            'FRUITS',     'UNIT',       'REFRIGERATOR'),
    ('lemon',           'Limón',               'Lemon',             'FRUITS',     'UNIT',       'REFRIGERATOR'),
    ('pear',            'Pera',                'Pear',              'FRUITS',     'UNIT',       'REFRIGERATOR'),
    ('strawberry',      'Fresas',              'Strawberries',      'FRUITS',     'GRAM',       'REFRIGERATOR'),
    ('grapes',          'Uvas',                'Grapes',            'FRUITS',     'GRAM',       'REFRIGERATOR'),
    ('avocado',         'Aguacate',            'Avocado',           'FRUITS',     'UNIT',       'PANTRY'),
    ('peach',           'Melocotón',           'Peach',             'FRUITS',     'UNIT',       'REFRIGERATOR'),
    ('watermelon',      'Sandía',              'Watermelon',        'FRUITS',     'UNIT',       'REFRIGERATOR'),
    ('melon',           'Melón',               'Melon',             'FRUITS',     'UNIT',       'REFRIGERATOR'),
    ('chicken-breast',  'Pechuga de pollo',    'Chicken breast',    'MEAT',       'GRAM',       'REFRIGERATOR'),
    ('chicken-thigh',   'Muslo de pollo',      'Chicken thigh',     'MEAT',       'GRAM',       'REFRIGERATOR'),
    ('minced-beef',     'Carne picada',        'Minced meat',       'MEAT',       'GRAM',       'REFRIGERATOR'),
    ('beef-steak',      'Filete de ternera',   'Beef steak',        'MEAT',       'GRAM',       'REFRIGERATOR'),
    ('pork-loin',       'Lomo de cerdo',       'Pork loin',         'MEAT',       'GRAM',       'REFRIGERATOR'),
    ('serrano-ham',     'Jamón serrano',       'Serrano ham',       'MEAT',       'GRAM',       'REFRIGERATOR'),
    ('cooked-ham',      'Jamón cocido',        'Cooked ham',        'MEAT',       'GRAM',       'REFRIGERATOR'),
    ('chorizo',         'Chorizo',             'Chorizo',           'MEAT',       'GRAM',       'REFRIGERATOR'),
    ('bacon',           'Beicon',              'Bacon',             'MEAT',       'GRAM',       'REFRIGERATOR'),
    ('salmon',          'Salmón',              'Salmon',            'FISH',       'GRAM',       'REFRIGERATOR'),
    ('hake',            'Merluza',             'Hake',              'FISH',       'GRAM',       'REFRIGERATOR'),
    ('prawns',          'Gambas',              'Prawns',            'FISH',       'GRAM',       'REFRIGERATOR'),
    ('canned-tuna',     'Atún en lata',        'Canned tuna',       'FISH',       'UNIT',       'PANTRY'),
    ('milk',            'Leche',               'Milk',              'DAIRY',      'LITER',      'REFRIGERATOR'),
    ('yogurt',          'Yogur',               'Yogurt',            'DAIRY',      'UNIT',       'REFRIGERATOR'),
    ('butter',          'Mantequilla',         'Butter',            'DAIRY',      'GRAM',       'REFRIGERATOR'),
    ('cheese',          'Queso',               'Cheese',            'DAIRY',      'GRAM',       'REFRIGERATOR'),
    ('mozzarella',      'Mozzarella',          'Mozzarella',        'DAIRY',      'GRAM',       'REFRIGERATOR'),
    ('cream',           'Nata para cocinar',   'Cooking cream',     'DAIRY',      'MILLILITER', 'REFRIGERATOR'),
    ('egg',             'Huevos',              'Eggs',              'EGGS',       'UNIT',       'REFRIGERATOR'),
    ('bread',           'Pan',                 'Bread',             'BAKERY',     'UNIT',       'PANTRY'),
    ('sliced-bread',    'Pan de molde',        'Sliced bread',      'BAKERY',     'UNIT',       'PANTRY'),
    ('rice',            'Arroz',               'Rice',              'PANTRY',     'GRAM',       'PANTRY'),
    ('pasta',           'Pasta',               'Pasta',             'PANTRY',     'GRAM',       'PANTRY'),
    ('flour',           'Harina',              'Flour',             'PANTRY',     'GRAM',       'PANTRY'),
    ('sugar',           'Azúcar',              'Sugar',             'PANTRY',     'GRAM',       'PANTRY'),
    ('salt',            'Sal',                 'Salt',              'PANTRY',     'GRAM',       'PANTRY'),
    ('olive-oil',       'Aceite de oliva',     'Olive oil',         'PANTRY',     'LITER',      'PANTRY'),
    ('vinegar',         'Vinagre',             'Vinegar',           'PANTRY',     'MILLILITER', 'PANTRY'),
    ('lentils',         'Lentejas',            'Lentils',           'PANTRY',     'GRAM',       'PANTRY'),
    ('chickpeas',       'Garbanzos',           'Chickpeas',         'PANTRY',     'GRAM',       'PANTRY'),
    ('white-beans',     'Alubias',             'White beans',       'PANTRY',     'GRAM',       'PANTRY'),
    ('crushed-tomato',  'Tomate triturado',    'Crushed tomato',    'PANTRY',     'GRAM',       'PANTRY'),
    ('fried-tomato',    'Tomate frito',        'Tomato sauce',      'PANTRY',     'GRAM',       'PANTRY'),
    ('soy-sauce',       'Salsa de soja',       'Soy sauce',         'PANTRY',     'MILLILITER', 'PANTRY'),
    ('coffee',          'Café',                'Coffee',            'PANTRY',     'GRAM',       'PANTRY'),
    ('breakfast-cereal','Cereales',            'Breakfast cereal',  'PANTRY',     'GRAM',       'PANTRY'),
    ('biscuits',        'Galletas',            'Biscuits',          'PANTRY',     'UNIT',       'PANTRY'),
    ('chocolate',       'Chocolate',           'Chocolate',         'PANTRY',     'GRAM',       'PANTRY'),
    ('frozen-peas',     'Guisantes congelados','Frozen peas',       'FROZEN',     'GRAM',       'FREEZER'),
    ('frozen-pizza',    'Pizza congelada',     'Frozen pizza',      'FROZEN',     'UNIT',       'FREEZER'),
    ('ice-cream',       'Helado',              'Ice cream',         'FROZEN',     'UNIT',       'FREEZER'),
    ('water',           'Agua',                'Water',             'BEVERAGES',  'LITER',      'PANTRY'),
    ('orange-juice',    'Zumo de naranja',     'Orange juice',      'BEVERAGES',  'LITER',      'REFRIGERATOR'),
    ('beer',            'Cerveza',             'Beer',              'BEVERAGES',  'UNIT',       'REFRIGERATOR'),
    ('wine',            'Vino',                'Wine',              'BEVERAGES',  'UNIT',       'PANTRY'),
    ('hummus',          'Hummus',              'Hummus',            'PREPARED',   'GRAM',       'REFRIGERATOR'),
    ('gazpacho',        'Gazpacho',            'Gazpacho',          'PREPARED',   'LITER',      'REFRIGERATOR'),
    ('spanish-omelette','Tortilla de patatas', 'Spanish omelette',  'PREPARED',   'UNIT',       'REFRIGERATOR');

create table food_items (
    id                uuid          primary key,
    household_id      uuid          not null references households (id) on delete cascade,
    food_id           uuid          references foods (id),
    name              varchar(120)  not null,
    -- Lower case and without accents, for searching.
    search_name       varchar(120)  not null,
    category          varchar(16)   not null,
    quantity          numeric(12,3) not null,
    unit              varchar(16)   not null,
    storage_location  varchar(16)   not null,
    status            varchar(16)   not null,
    purchase_date     date          not null,
    expiration_date   date,
    expiration_source varchar(16),
    opened_date       date,
    barcode           varchar(32),
    brand             varchar(80),
    estimated_price   numeric(10,2),
    notes             varchar(500),
    created_by        uuid          references users (id) on delete set null,
    created_at        timestamptz   not null,
    updated_at        timestamptz   not null,
    version           bigint        not null,
    constraint ck_food_items_quantity check (quantity >= 0),
    constraint ck_food_items_price check (estimated_price is null or estimated_price >= 0),
    constraint ck_food_items_status
        check (status in ('AVAILABLE', 'OPENED', 'CONSUMED', 'EXPIRED', 'DISCARDED')),
    -- A date always says where it came from, so an estimate can never pass for a real one.
    constraint ck_food_items_expiration
        check ((expiration_date is null) = (expiration_source is null)),
    constraint ck_food_items_expiration_source
        check (expiration_source is null or expiration_source in ('USER', 'ESTIMATED'))
);
create index ix_food_items_household_status on food_items (household_id, status, expiration_date);

-- What happened to food that left the inventory: the basis of the consumption and waste statistics.
create table food_outcomes (
    id              uuid          primary key,
    household_id    uuid          not null references households (id) on delete cascade,
    food_item_id    uuid          references food_items (id) on delete set null,
    food_id         uuid          references foods (id),
    name            varchar(120)  not null,
    category        varchar(16)   not null,
    type            varchar(16)   not null,
    reason          varchar(16),
    quantity        numeric(12,3) not null,
    unit            varchar(16)   not null,
    estimated_value numeric(10,2),
    recorded_by     uuid          references users (id) on delete set null,
    occurred_at     timestamptz   not null,
    constraint ck_food_outcomes_type check (type in ('CONSUMED', 'DISCARDED')),
    constraint ck_food_outcomes_reason check ((type = 'DISCARDED') = (reason is not null))
);
create index ix_food_outcomes_household on food_outcomes (household_id, occurred_at);

create table product_events (
    id           uuid         primary key,
    name         varchar(64)  not null,
    user_id      uuid,
    household_id uuid,
    occurred_at  timestamptz  not null
);
create index ix_product_events_name on product_events (name, occurred_at);
