-- Recipes. Rows are added by migrations only; the texts are the project's own.
create table recipes (
    id             uuid         primary key default gen_random_uuid(),
    slug           varchar(64)  not null,
    name_es        varchar(120) not null,
    name_en        varchar(120) not null,
    description_es varchar(300) not null,
    description_en varchar(300) not null,
    servings       integer      not null,
    prep_minutes   integer      not null,
    cook_minutes   integer      not null,
    difficulty     varchar(16)  not null,
    course         varchar(16)  not null,
    -- One step per line.
    steps_es       text         not null,
    steps_en       text         not null,
    constraint uq_recipes_slug unique (slug),
    constraint ck_recipes_servings check (servings > 0),
    constraint ck_recipes_minutes check (prep_minutes >= 0 and cook_minutes >= 0),
    constraint ck_recipes_difficulty check (difficulty in ('EASY', 'MEDIUM', 'HARD')),
    constraint ck_recipes_course check (course in ('BREAKFAST', 'MAIN', 'DESSERT'))
);

-- Every ingredient is a food of the catalog with a quantity: that is what lets a recipe be matched against
-- an inventory. "staple" marks what a kitchen is assumed to have (salt, oil, water, garlic): it is listed in
-- the recipe but never counted as missing.
create table recipe_ingredients (
    recipe_id uuid          not null references recipes (id) on delete cascade,
    position  integer       not null,
    food_id   uuid          not null references foods (id),
    amount    numeric(12,3) not null,
    unit      varchar(16)   not null,
    staple    boolean       not null,
    primary key (recipe_id, position),
    constraint uq_recipe_ingredients_food unique (recipe_id, food_id),
    constraint ck_recipe_ingredients_amount check (amount > 0)
);
create index ix_recipe_ingredients_food on recipe_ingredients (food_id);

-- A household said it cooked a recipe. Used to avoid suggesting the same thing day after day.
create table cooked_recipes (
    id           uuid        primary key,
    household_id uuid        not null references households (id) on delete cascade,
    recipe_id    uuid        not null references recipes (id) on delete cascade,
    cooked_by    uuid        references users (id) on delete set null,
    cooked_on    date        not null,
    created_at   timestamptz not null,
    constraint uq_cooked_recipes_day unique (household_id, recipe_id, cooked_on)
);
create index ix_cooked_recipes_household on cooked_recipes (household_id, cooked_on desc);

insert into recipes
    (slug, name_es, name_en, description_es, description_en, servings, prep_minutes, cook_minutes, difficulty, course,
     steps_es, steps_en)
values
    ('spanish-omelette', 'Tortilla de patatas', 'Spanish omelette',
     'La de siempre, con cebolla.', 'The classic one, with onion.', 4, 15, 25, 'MEDIUM', 'MAIN',
     E'Pela y corta las patatas y la cebolla en láminas finas.\nFríelas a fuego suave en abundante aceite hasta que estén tiernas y escúrrelas.\nBate los huevos con sal y mézclalos con las patatas y la cebolla.\nCuaja la mezcla en una sartén con un poco de aceite, dale la vuelta con un plato y cuaja el otro lado.',
     E'Peel the potatoes and the onion and slice them thinly.\nFry them gently in plenty of oil until tender, then drain.\nBeat the eggs with salt and mix them with the potatoes and onion.\nSet the mixture in a pan with a little oil, flip it with a plate and set the other side.'),
    ('pasta-zucchini-tomato', 'Pasta con calabacín y tomate', 'Pasta with zucchini and tomato',
     'Un plato rápido que aprovecha el calabacín y los tomates maduros.', 'A quick dish for zucchini and ripe tomatoes.', 2, 10, 15, 'EASY', 'MAIN',
     E'Cuece la pasta en agua con sal.\nSaltea el ajo picado y el calabacín en dados con aceite.\nAñade los tomates troceados y cocina cinco minutos.\nMezcla con la pasta escurrida y reparte la mozzarella en trozos por encima.',
     E'Boil the pasta in salted water.\nFry the chopped garlic and the diced zucchini in oil.\nAdd the chopped tomatoes and cook for five minutes.\nToss with the drained pasta and scatter the torn mozzarella on top.'),
    ('chicken-rice-vegetables', 'Arroz con pollo y verduras', 'Rice with chicken and vegetables',
     'Arroz meloso de diario con lo que haya en la nevera.', 'An everyday rice dish with what is in the fridge.', 2, 15, 30, 'MEDIUM', 'MAIN',
     E'Dora el pollo en dados con aceite y resérvalo.\nSofríe la cebolla y el pimiento picados y añade el tomate triturado.\nIncorpora el arroz, el pollo y el doble de agua que de arroz, con sal.\nCuece dieciocho minutos y añade los guisantes en los últimos cinco.',
     E'Brown the diced chicken in oil and set it aside.\nFry the chopped onion and pepper and add the crushed tomato.\nAdd the rice, the chicken and twice as much water as rice, with salt.\nCook for eighteen minutes, adding the peas for the last five.'),
    ('lentils-vegetables', 'Lentejas con verduras', 'Lentils with vegetables',
     'Un guiso de cuchara sin carne.', 'A meatless stew.', 4, 15, 45, 'EASY', 'MAIN',
     E'Pica la cebolla, el puerro, la zanahoria y el ajo y sofríelos con aceite.\nAñade las lentejas, la patata en trozos y agua hasta cubrir tres dedos.\nCuece a fuego suave unos cuarenta minutos, hasta que las lentejas estén tiernas.\nRectifica de sal al final.',
     E'Chop the onion, leek, carrot and garlic and fry them in oil.\nAdd the lentils, the potato in chunks and water to cover by three fingers.\nSimmer for about forty minutes, until the lentils are tender.\nSeason with salt at the end.'),
    ('lentils-chorizo', 'Lentejas con chorizo', 'Lentils with chorizo',
     'Las lentejas tradicionales.', 'Traditional lentils.', 4, 15, 45, 'EASY', 'MAIN',
     E'Sofríe la cebolla y la zanahoria picadas con el ajo.\nAñade el chorizo en rodajas, las lentejas, la patata en trozos y agua hasta cubrir tres dedos.\nCuece a fuego suave unos cuarenta minutos.\nRectifica de sal al final.',
     E'Fry the chopped onion and carrot with the garlic.\nAdd the sliced chorizo, the lentils, the potato in chunks and water to cover by three fingers.\nSimmer for about forty minutes.\nSeason with salt at the end.'),
    ('pumpkin-soup', 'Crema de calabaza', 'Pumpkin soup',
     'Suave y reconfortante.', 'Smooth and comforting.', 4, 10, 30, 'EASY', 'MAIN',
     E'Rehoga el puerro picado con aceite.\nAñade la calabaza y la patata en trozos, cubre con agua y sal y cuece veinticinco minutos.\nTritura hasta que quede fina y añade la nata.',
     E'Soften the chopped leek in oil.\nAdd the pumpkin and potato in chunks, cover with salted water and cook for twenty-five minutes.\nBlend until smooth and stir in the cream.'),
    ('zucchini-soup', 'Crema de calabacín', 'Zucchini soup',
     'Una crema ligera para cuando sobra calabacín.', 'A light soup for spare zucchini.', 4, 10, 25, 'EASY', 'MAIN',
     E'Rehoga la cebolla picada con aceite.\nAñade el calabacín y la patata en trozos, cubre con agua y sal y cuece veinte minutos.\nTritura con el queso hasta que quede fina.',
     E'Soften the chopped onion in oil.\nAdd the zucchini and potato in chunks, cover with salted water and cook for twenty minutes.\nBlend with the cheese until smooth.'),
    ('scrambled-eggs-mushrooms', 'Revuelto de champiñones', 'Scrambled eggs with mushrooms',
     'Una cena en diez minutos.', 'Dinner in ten minutes.', 2, 5, 10, 'EASY', 'MAIN',
     E'Lamina los champiñones y saltéalos con el ajo picado y aceite hasta que pierdan el agua.\nAñade los huevos batidos con sal.\nRemueve a fuego suave hasta que cuajen sin secarse.',
     E'Slice the mushrooms and fry them with the chopped garlic in oil until their water is gone.\nAdd the eggs beaten with salt.\nStir over a gentle heat until set but still moist.'),
    ('chickpea-salad', 'Ensalada de garbanzos', 'Chickpea salad',
     'Fría, sin cocinar y completa.', 'Cold, no cooking and filling.', 2, 15, 0, 'EASY', 'MAIN',
     E'Escurre y lava los garbanzos cocidos.\nTrocea el tomate, el pepino y la cebolla.\nMezcla todo con el atún y aliña con aceite, vinagre y sal.',
     E'Drain and rinse the cooked chickpeas.\nChop the tomato, cucumber and onion.\nMix everything with the tuna and dress with oil, vinegar and salt.'),
    ('grilled-chicken-broccoli', 'Pollo a la plancha con brócoli', 'Grilled chicken with broccoli',
     'Sencillo y ligero.', 'Simple and light.', 2, 10, 15, 'EASY', 'MAIN',
     E'Cuece el brócoli en ramilletes en agua con sal cinco minutos y escúrrelo.\nHaz las pechugas a la plancha con un poco de aceite y sal.\nSirve con zumo de limón por encima.',
     E'Boil the broccoli florets in salted water for five minutes and drain.\nGrill the chicken breasts with a little oil and salt.\nServe with lemon juice squeezed over.'),
    ('baked-salmon-potatoes', 'Salmón al horno con patatas', 'Baked salmon with potatoes',
     'Todo en una bandeja.', 'Everything in one tray.', 2, 10, 30, 'EASY', 'MAIN',
     E'Corta las patatas y la cebolla en rodajas finas y ponlas en una bandeja con aceite y sal.\nHornéalas quince minutos a 200 grados.\nColoca el salmón encima con rodajas de limón y hornea doce minutos más.',
     E'Slice the potatoes and onion thinly and put them in a tray with oil and salt.\nBake them for fifteen minutes at 200 degrees.\nPut the salmon on top with lemon slices and bake for twelve more minutes.'),
    ('hake-green-peas', 'Merluza con guisantes', 'Hake with peas',
     'Merluza en una salsa ligera con guisantes.', 'Hake in a light sauce with peas.', 2, 10, 15, 'MEDIUM', 'MAIN',
     E'Dora el ajo picado con aceite y añade la harina, removiendo.\nVierte un vaso de agua poco a poco hasta tener una salsa ligera.\nAñade los guisantes y la merluza salada y cuece ocho minutos a fuego suave.',
     E'Brown the chopped garlic in oil and stir in the flour.\nPour in a glass of water little by little to make a light sauce.\nAdd the peas and the salted hake and simmer for eight minutes.'),
    ('spinach-chickpeas', 'Espinacas con garbanzos', 'Spinach with chickpeas',
     'Un clásico rápido de legumbre y verdura.', 'A quick classic of pulses and greens.', 2, 10, 15, 'EASY', 'MAIN',
     E'Dora el ajo laminado con aceite.\nAñade el tomate triturado y cocina cinco minutos.\nIncorpora las espinacas y, cuando reduzcan, los garbanzos cocidos escurridos.\nCocina cinco minutos más y ajusta de sal.',
     E'Brown the sliced garlic in oil.\nAdd the crushed tomato and cook for five minutes.\nAdd the spinach and, once it wilts, the drained cooked chickpeas.\nCook for five more minutes and season with salt.'),
    ('pisto-egg', 'Pisto con huevo', 'Pisto with egg',
     'El plato para aprovechar las verduras de la nevera.', 'The dish for using up the vegetables in the fridge.', 2, 15, 35, 'EASY', 'MAIN',
     E'Corta todas las verduras en dados pequeños.\nSofríe la cebolla y los pimientos con aceite; añade la berenjena y el calabacín a los diez minutos.\nIncorpora el tomate triturado con sal y cocina veinte minutos a fuego suave.\nSirve con un huevo a la plancha por persona.',
     E'Dice all the vegetables small.\nFry the onion and peppers in oil; add the eggplant and zucchini after ten minutes.\nAdd the crushed tomato with salt and cook gently for twenty minutes.\nServe with one fried egg per person.'),
    ('pasta-minced-beef', 'Macarrones con carne', 'Pasta with minced meat',
     'Los macarrones de toda la vida.', 'Everyday pasta with meat sauce.', 2, 10, 20, 'EASY', 'MAIN',
     E'Cuece la pasta en agua con sal.\nSofríe la cebolla picada con aceite y dora la carne picada.\nAñade el tomate frito y cocina cinco minutos.\nMezcla con la pasta y ralla el queso por encima.',
     E'Boil the pasta in salted water.\nFry the chopped onion in oil and brown the minced meat.\nAdd the tomato sauce and cook for five minutes.\nToss with the pasta and grate the cheese on top.'),
    ('fried-rice-prawns', 'Arroz salteado con gambas', 'Fried rice with prawns',
     'Ideal para aprovechar arroz y verduras sueltas.', 'Good for spare rice and odd vegetables.', 2, 15, 20, 'MEDIUM', 'MAIN',
     E'Cuece el arroz en agua con sal y escúrrelo.\nSaltea la zanahoria en dados y los guisantes con aceite; añade las gambas peladas.\nIncorpora el arroz y el huevo batido, removiendo hasta que cuaje.\nAliña con la salsa de soja.',
     E'Boil the rice in salted water and drain it.\nFry the diced carrot and the peas in oil; add the peeled prawns.\nAdd the rice and the beaten egg, stirring until it sets.\nSeason with the soy sauce.'),
    ('pasta-tuna-salad', 'Ensalada de pasta con atún', 'Pasta salad with tuna',
     'Para llevar o para una cena fría.', 'To take away or for a cold dinner.', 2, 10, 12, 'EASY', 'MAIN',
     E'Cuece la pasta en agua con sal, escúrrela y enfríala.\nCuece los huevos diez minutos, pélalos y trocéalos.\nMezcla la pasta con el tomate troceado, el atún y el huevo.\nAliña con aceite y sal.',
     E'Boil the pasta in salted water, drain and cool it.\nBoil the eggs for ten minutes, peel and chop them.\nMix the pasta with the chopped tomato, the tuna and the egg.\nDress with oil and salt.'),
    ('avocado-egg-toast', 'Tostadas de aguacate y huevo', 'Avocado and egg toast',
     'Para cuando el aguacate ya está maduro.', 'For when the avocado is ripe.', 2, 5, 5, 'EASY', 'BREAKFAST',
     E'Tuesta el pan.\nAplasta el aguacate con zumo de limón y sal y úntalo en las tostadas.\nHaz los huevos a la plancha con un poco de aceite y ponlos encima.',
     E'Toast the bread.\nMash the avocado with lemon juice and salt and spread it on the toast.\nFry the eggs with a little oil and put them on top.'),
    ('vegetable-stew-ham', 'Menestra de verduras con jamón', 'Vegetable stew with ham',
     'Verduras salteadas con un poco de jamón.', 'Vegetables finished with a little ham.', 2, 15, 25, 'EASY', 'MAIN',
     E'Cuece las judías verdes, la zanahoria y la patata troceadas en agua con sal quince minutos.\nAñade los guisantes y cuece cinco minutos más; escurre.\nSaltea el jamón en tiras con el ajo y aceite y mezcla con las verduras.',
     E'Boil the chopped green beans, carrot and potato in salted water for fifteen minutes.\nAdd the peas and cook for five more minutes; drain.\nFry the ham in strips with the garlic in oil and mix with the vegetables.'),
    ('yogurt-fruit', 'Yogur con fruta y cereales', 'Yogurt with fruit and cereal',
     'Un desayuno que aprovecha la fruta madura.', 'A breakfast for ripe fruit.', 2, 5, 0, 'EASY', 'BREAKFAST',
     E'Trocea el plátano y las fresas.\nReparte el yogur en dos cuencos.\nAñade la fruta y los cereales por encima.',
     E'Chop the banana and the strawberries.\nDivide the yogurt between two bowls.\nTop with the fruit and the cereal.'),
    ('banana-smoothie', 'Batido de plátano', 'Banana smoothie',
     'Para los plátanos demasiado maduros.', 'For bananas that are too ripe.', 2, 5, 0, 'EASY', 'BREAKFAST',
     E'Pela los plátanos y trocéalos.\nTritúralos con la leche fría hasta que no queden trozos.',
     E'Peel and chop the bananas.\nBlend them with the cold milk until smooth.'),
    ('torrijas', 'Torrijas', 'Spanish-style French toast',
     'El mejor destino del pan del día anterior.', 'The best use for yesterday''s bread.', 4, 10, 15, 'MEDIUM', 'DESSERT',
     E'Corta el pan en rebanadas gruesas.\nCalienta la leche con la mitad del azúcar y empapa bien las rebanadas.\nPásalas por huevo batido y fríelas en aceite hasta que se doren.\nEspolvorea el resto del azúcar por encima.',
     E'Cut the bread into thick slices.\nWarm the milk with half the sugar and soak the slices well.\nDip them in beaten egg and fry in oil until golden.\nSprinkle the rest of the sugar on top.'),
    ('ham-cheese-sandwich', 'Sándwich mixto', 'Ham and cheese toastie',
     'Lo más rápido que hay.', 'As quick as it gets.', 2, 5, 5, 'EASY', 'MAIN',
     E'Unta el pan de molde con mantequilla por fuera.\nRellena con el jamón cocido y el queso.\nDora los sándwiches en una sartén por los dos lados hasta que el queso se funda.',
     E'Butter the outside of the bread.\nFill with the cooked ham and the cheese.\nBrown the sandwiches in a pan on both sides until the cheese melts.'),
    ('beef-steak-peppers', 'Filete de ternera con pimientos', 'Beef steak with peppers',
     'Carne a la plancha con pimientos y patatas.', 'Grilled beef with peppers and potatoes.', 2, 10, 20, 'EASY', 'MAIN',
     E'Fríe las patatas en dados con aceite hasta que estén doradas.\nSaltea los pimientos en tiras con un poco de aceite y sal.\nHaz los filetes a la plancha a fuego fuerte y sálalos al final.',
     E'Fry the diced potatoes in oil until golden.\nFry the peppers in strips with a little oil and salt.\nGrill the steaks over a high heat and salt them at the end.'),
    ('pork-loin-mushrooms', 'Lomo con champiñones', 'Pork loin with mushrooms',
     'Lomo en una salsa rápida de champiñones.', 'Pork loin in a quick mushroom sauce.', 2, 10, 20, 'EASY', 'MAIN',
     E'Dora el lomo en filetes con aceite y sal y resérvalo.\nSofríe la cebolla picada y los champiñones laminados en la misma sartén.\nAñade la nata, devuelve el lomo y cocina cinco minutos.',
     E'Brown the sliced pork loin in oil with salt and set it aside.\nFry the chopped onion and the sliced mushrooms in the same pan.\nAdd the cream, return the pork and cook for five minutes.');

insert into recipe_ingredients (recipe_id, position, food_id, amount, unit, staple)
select r.id, v.position, f.id, v.amount, v.unit, v.staple
from (values
    ('spanish-omelette', 1, 'potato', 500, 'GRAM', false),
    ('spanish-omelette', 2, 'egg', 4, 'UNIT', false),
    ('spanish-omelette', 3, 'onion', 1, 'UNIT', false),
    ('spanish-omelette', 4, 'olive-oil', 200, 'MILLILITER', true),
    ('spanish-omelette', 5, 'salt', 3, 'GRAM', true),

    ('pasta-zucchini-tomato', 1, 'pasta', 200, 'GRAM', false),
    ('pasta-zucchini-tomato', 2, 'zucchini', 1, 'UNIT', false),
    ('pasta-zucchini-tomato', 3, 'tomato', 2, 'UNIT', false),
    ('pasta-zucchini-tomato', 4, 'mozzarella', 100, 'GRAM', false),
    ('pasta-zucchini-tomato', 5, 'garlic', 1, 'UNIT', true),
    ('pasta-zucchini-tomato', 6, 'olive-oil', 20, 'MILLILITER', true),
    ('pasta-zucchini-tomato', 7, 'salt', 3, 'GRAM', true),

    ('chicken-rice-vegetables', 1, 'rice', 200, 'GRAM', false),
    ('chicken-rice-vegetables', 2, 'chicken-breast', 300, 'GRAM', false),
    ('chicken-rice-vegetables', 3, 'red-pepper', 1, 'UNIT', false),
    ('chicken-rice-vegetables', 4, 'onion', 1, 'UNIT', false),
    ('chicken-rice-vegetables', 5, 'frozen-peas', 100, 'GRAM', false),
    ('chicken-rice-vegetables', 6, 'crushed-tomato', 100, 'GRAM', false),
    ('chicken-rice-vegetables', 7, 'olive-oil', 30, 'MILLILITER', true),
    ('chicken-rice-vegetables', 8, 'salt', 3, 'GRAM', true),

    ('lentils-vegetables', 1, 'lentils', 250, 'GRAM', false),
    ('lentils-vegetables', 2, 'carrot', 2, 'UNIT', false),
    ('lentils-vegetables', 3, 'onion', 1, 'UNIT', false),
    ('lentils-vegetables', 4, 'potato', 200, 'GRAM', false),
    ('lentils-vegetables', 5, 'leek', 1, 'UNIT', false),
    ('lentils-vegetables', 6, 'garlic', 1, 'UNIT', true),
    ('lentils-vegetables', 7, 'olive-oil', 30, 'MILLILITER', true),
    ('lentils-vegetables', 8, 'salt', 4, 'GRAM', true),

    ('lentils-chorizo', 1, 'lentils', 250, 'GRAM', false),
    ('lentils-chorizo', 2, 'chorizo', 100, 'GRAM', false),
    ('lentils-chorizo', 3, 'carrot', 1, 'UNIT', false),
    ('lentils-chorizo', 4, 'onion', 1, 'UNIT', false),
    ('lentils-chorizo', 5, 'potato', 200, 'GRAM', false),
    ('lentils-chorizo', 6, 'garlic', 1, 'UNIT', true),
    ('lentils-chorizo', 7, 'salt', 4, 'GRAM', true),

    ('pumpkin-soup', 1, 'pumpkin', 600, 'GRAM', false),
    ('pumpkin-soup', 2, 'potato', 200, 'GRAM', false),
    ('pumpkin-soup', 3, 'leek', 1, 'UNIT', false),
    ('pumpkin-soup', 4, 'cream', 100, 'MILLILITER', false),
    ('pumpkin-soup', 5, 'olive-oil', 20, 'MILLILITER', true),
    ('pumpkin-soup', 6, 'salt', 4, 'GRAM', true),

    ('zucchini-soup', 1, 'zucchini', 2, 'UNIT', false),
    ('zucchini-soup', 2, 'potato', 200, 'GRAM', false),
    ('zucchini-soup', 3, 'onion', 1, 'UNIT', false),
    ('zucchini-soup', 4, 'cheese', 50, 'GRAM', false),
    ('zucchini-soup', 5, 'olive-oil', 20, 'MILLILITER', true),
    ('zucchini-soup', 6, 'salt', 4, 'GRAM', true),

    ('scrambled-eggs-mushrooms', 1, 'mushroom', 250, 'GRAM', false),
    ('scrambled-eggs-mushrooms', 2, 'egg', 4, 'UNIT', false),
    ('scrambled-eggs-mushrooms', 3, 'garlic', 1, 'UNIT', true),
    ('scrambled-eggs-mushrooms', 4, 'olive-oil', 20, 'MILLILITER', true),
    ('scrambled-eggs-mushrooms', 5, 'salt', 2, 'GRAM', true),

    ('chickpea-salad', 1, 'chickpeas', 400, 'GRAM', false),
    ('chickpea-salad', 2, 'tomato', 2, 'UNIT', false),
    ('chickpea-salad', 3, 'cucumber', 1, 'UNIT', false),
    ('chickpea-salad', 4, 'onion', 1, 'UNIT', false),
    ('chickpea-salad', 5, 'canned-tuna', 1, 'UNIT', false),
    ('chickpea-salad', 6, 'olive-oil', 30, 'MILLILITER', true),
    ('chickpea-salad', 7, 'vinegar', 10, 'MILLILITER', true),
    ('chickpea-salad', 8, 'salt', 2, 'GRAM', true),

    ('grilled-chicken-broccoli', 1, 'chicken-breast', 300, 'GRAM', false),
    ('grilled-chicken-broccoli', 2, 'broccoli', 1, 'UNIT', false),
    ('grilled-chicken-broccoli', 3, 'lemon', 1, 'UNIT', false),
    ('grilled-chicken-broccoli', 4, 'olive-oil', 15, 'MILLILITER', true),
    ('grilled-chicken-broccoli', 5, 'salt', 2, 'GRAM', true),

    ('baked-salmon-potatoes', 1, 'salmon', 300, 'GRAM', false),
    ('baked-salmon-potatoes', 2, 'potato', 400, 'GRAM', false),
    ('baked-salmon-potatoes', 3, 'onion', 1, 'UNIT', false),
    ('baked-salmon-potatoes', 4, 'lemon', 1, 'UNIT', false),
    ('baked-salmon-potatoes', 5, 'olive-oil', 30, 'MILLILITER', true),
    ('baked-salmon-potatoes', 6, 'salt', 3, 'GRAM', true),

    ('hake-green-peas', 1, 'hake', 400, 'GRAM', false),
    ('hake-green-peas', 2, 'frozen-peas', 100, 'GRAM', false),
    ('hake-green-peas', 3, 'flour', 10, 'GRAM', false),
    ('hake-green-peas', 4, 'garlic', 2, 'UNIT', true),
    ('hake-green-peas', 5, 'olive-oil', 30, 'MILLILITER', true),
    ('hake-green-peas', 6, 'salt', 3, 'GRAM', true),

    ('spinach-chickpeas', 1, 'spinach', 300, 'GRAM', false),
    ('spinach-chickpeas', 2, 'chickpeas', 400, 'GRAM', false),
    ('spinach-chickpeas', 3, 'crushed-tomato', 100, 'GRAM', false),
    ('spinach-chickpeas', 4, 'garlic', 2, 'UNIT', true),
    ('spinach-chickpeas', 5, 'olive-oil', 30, 'MILLILITER', true),
    ('spinach-chickpeas', 6, 'salt', 3, 'GRAM', true),

    ('pisto-egg', 1, 'zucchini', 1, 'UNIT', false),
    ('pisto-egg', 2, 'eggplant', 1, 'UNIT', false),
    ('pisto-egg', 3, 'red-pepper', 1, 'UNIT', false),
    ('pisto-egg', 4, 'green-pepper', 1, 'UNIT', false),
    ('pisto-egg', 5, 'onion', 1, 'UNIT', false),
    ('pisto-egg', 6, 'crushed-tomato', 400, 'GRAM', false),
    ('pisto-egg', 7, 'egg', 2, 'UNIT', false),
    ('pisto-egg', 8, 'olive-oil', 40, 'MILLILITER', true),
    ('pisto-egg', 9, 'salt', 4, 'GRAM', true),

    ('pasta-minced-beef', 1, 'pasta', 200, 'GRAM', false),
    ('pasta-minced-beef', 2, 'minced-beef', 250, 'GRAM', false),
    ('pasta-minced-beef', 3, 'onion', 1, 'UNIT', false),
    ('pasta-minced-beef', 4, 'fried-tomato', 200, 'GRAM', false),
    ('pasta-minced-beef', 5, 'cheese', 40, 'GRAM', false),
    ('pasta-minced-beef', 6, 'olive-oil', 20, 'MILLILITER', true),
    ('pasta-minced-beef', 7, 'salt', 3, 'GRAM', true),

    ('fried-rice-prawns', 1, 'rice', 200, 'GRAM', false),
    ('fried-rice-prawns', 2, 'prawns', 200, 'GRAM', false),
    ('fried-rice-prawns', 3, 'carrot', 1, 'UNIT', false),
    ('fried-rice-prawns', 4, 'frozen-peas', 80, 'GRAM', false),
    ('fried-rice-prawns', 5, 'egg', 1, 'UNIT', false),
    ('fried-rice-prawns', 6, 'soy-sauce', 20, 'MILLILITER', false),
    ('fried-rice-prawns', 7, 'olive-oil', 20, 'MILLILITER', true),
    ('fried-rice-prawns', 8, 'salt', 2, 'GRAM', true),

    ('pasta-tuna-salad', 1, 'pasta', 200, 'GRAM', false),
    ('pasta-tuna-salad', 2, 'canned-tuna', 2, 'UNIT', false),
    ('pasta-tuna-salad', 3, 'tomato', 2, 'UNIT', false),
    ('pasta-tuna-salad', 4, 'egg', 2, 'UNIT', false),
    ('pasta-tuna-salad', 5, 'olive-oil', 30, 'MILLILITER', true),
    ('pasta-tuna-salad', 6, 'salt', 3, 'GRAM', true),

    ('avocado-egg-toast', 1, 'sliced-bread', 4, 'UNIT', false),
    ('avocado-egg-toast', 2, 'avocado', 1, 'UNIT', false),
    ('avocado-egg-toast', 3, 'egg', 2, 'UNIT', false),
    ('avocado-egg-toast', 4, 'lemon', 1, 'UNIT', false),
    ('avocado-egg-toast', 5, 'olive-oil', 10, 'MILLILITER', true),
    ('avocado-egg-toast', 6, 'salt', 1, 'GRAM', true),

    ('vegetable-stew-ham', 1, 'green-beans', 200, 'GRAM', false),
    ('vegetable-stew-ham', 2, 'carrot', 2, 'UNIT', false),
    ('vegetable-stew-ham', 3, 'potato', 200, 'GRAM', false),
    ('vegetable-stew-ham', 4, 'frozen-peas', 100, 'GRAM', false),
    ('vegetable-stew-ham', 5, 'serrano-ham', 50, 'GRAM', false),
    ('vegetable-stew-ham', 6, 'garlic', 1, 'UNIT', true),
    ('vegetable-stew-ham', 7, 'olive-oil', 20, 'MILLILITER', true),
    ('vegetable-stew-ham', 8, 'salt', 3, 'GRAM', true),

    ('yogurt-fruit', 1, 'yogurt', 2, 'UNIT', false),
    ('yogurt-fruit', 2, 'banana', 1, 'UNIT', false),
    ('yogurt-fruit', 3, 'strawberry', 150, 'GRAM', false),
    ('yogurt-fruit', 4, 'breakfast-cereal', 40, 'GRAM', false),

    ('banana-smoothie', 1, 'banana', 2, 'UNIT', false),
    ('banana-smoothie', 2, 'milk', 400, 'MILLILITER', false),

    ('torrijas', 1, 'bread', 1, 'UNIT', false),
    ('torrijas', 2, 'milk', 500, 'MILLILITER', false),
    ('torrijas', 3, 'egg', 2, 'UNIT', false),
    ('torrijas', 4, 'sugar', 50, 'GRAM', false),
    ('torrijas', 5, 'olive-oil', 150, 'MILLILITER', true),

    ('ham-cheese-sandwich', 1, 'sliced-bread', 4, 'UNIT', false),
    ('ham-cheese-sandwich', 2, 'cooked-ham', 80, 'GRAM', false),
    ('ham-cheese-sandwich', 3, 'cheese', 60, 'GRAM', false),
    ('ham-cheese-sandwich', 4, 'butter', 10, 'GRAM', false),

    ('beef-steak-peppers', 1, 'beef-steak', 300, 'GRAM', false),
    ('beef-steak-peppers', 2, 'green-pepper', 2, 'UNIT', false),
    ('beef-steak-peppers', 3, 'potato', 300, 'GRAM', false),
    ('beef-steak-peppers', 4, 'olive-oil', 60, 'MILLILITER', true),
    ('beef-steak-peppers', 5, 'salt', 3, 'GRAM', true),

    ('pork-loin-mushrooms', 1, 'pork-loin', 300, 'GRAM', false),
    ('pork-loin-mushrooms', 2, 'mushroom', 200, 'GRAM', false),
    ('pork-loin-mushrooms', 3, 'onion', 1, 'UNIT', false),
    ('pork-loin-mushrooms', 4, 'cream', 100, 'MILLILITER', false),
    ('pork-loin-mushrooms', 5, 'olive-oil', 20, 'MILLILITER', true),
    ('pork-loin-mushrooms', 6, 'salt', 3, 'GRAM', true)
) as v (recipe, position, food, amount, unit, staple)
join recipes r on r.slug = v.recipe
join foods f on f.slug = v.food;

-- A typo in a slug above would silently drop a row from the join; fail the migration instead.
do $$
begin
    if (select count(*) from recipes) <> 25 then
        raise exception 'Expected 25 recipes, found %', (select count(*) from recipes);
    end if;
    if (select count(*) from recipe_ingredients) <> 153 then
        raise exception 'Expected 153 recipe ingredients, found %', (select count(*) from recipe_ingredients);
    end if;
end $$;
